### PR TITLE
Use erlef/setup-beam

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by RobertDober** [comment]
can you explain please? It does not seem to work 😢 
I guess this is some kind of best practice, some pointers would be nice.

Thanks in advance

**Comment by kianmeng** [comment]
@RobertDober Fixed. Please check again.

**Comment by RobertDober** [comment]
@kianmeng thank you for fixing, but please explain what this is about.

**Comment by kianmeng** [comment]
https://github.com/erlef/setup-elixir redirects to https://github.com/erlef/setup-beam.

**Pull request merged**
