### PR TITLE
Join multiple IAL `.class` directives with spaces

### PR DESCRIPTION
**Pull request by myrrlyn**
This change modifies the IAL folding logic from `[c1, c2]` to `"c1 c2"`. 
The current `to_string` behavior of `[String.t]` is concatenation with 
no interleaving spaces, which results in IALs of the form `{:.c1 .c2}` 
being serialized as `<tag class="c1c2">` rather than the intended 
`<tag class="c1 c2">`. After this change, multiple class directives in
an IAL are now serialized correctly in the HTML `class` attribute.

### CODE REVIEW

**Comment by myrrlyn** [comment]
This change may result in a performance regression, as folding the contents of an IAL now requires appending to the back of a `String` rather than appending to the head of a list. I have not attempted to measure it on IALs of any significant size.

I was unable to determine where IALs are serialized to HTML; that site *may* be more appropriate to change the current behavior, which for `[String.t()]` is concatenation, to an interleave of each list item and a space character. As I am unfamiliar with the allocation characteristics of the BEAM, I do not know if it is preferable to eagerly grow a `String.t()` or to carry a `[String.t()]` list and interleave list elements and spaces only at the serialization point.

However, this patch fixes the behavior of `{: .class1 .class2}` on my machine, emitting `class="class1 class2"` instead of `class="class1class2"`, matching [the IAL behavior of kramdown](https://babelmark.github.io/?text=%3E+Blockquote%0A%7B%3A.class1+.class2%7D)

**Comment by myrrlyn** [comment]
Note: the IAL syntax `{:.class1.class2}` (with *no* space between `.class1` and `.class2`) is interpreted by kramdown as `"class1 class2"` (separate classes), but by maruku as `"class1.class2"` (a single classname containing an intermediate period character).

Whether Earmark should parse this directive according to kramdown or maruku is out of scope of this PR, but Earmark *should* match both of them when serializing the separated class directives that it does unambiguously recognize.

**Comment by RobertDober** [comment]
Dear @myrrlyn 
I am really sorry I had no time to look at this earlier.
I *always* try to honor the efforts of all contributers but in this trying times I fell short.

I will do my best to integrate your PR ASAP but as you can see the CI is broken, it is an extremly easy fix though

```
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index f88b017..8aa74db 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,12 +11,12 @@ on:

 jobs:
   test:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-18.04
```

Would be great if you could apply this patch to get us to green here.

Thank you so much again.

P.S. Nice of you to mention a potential performance problem, but aside from a deliberate DoS attack I consider 
the length of an IAL to be bound somewhere around 10 ;).
Furthermore the DoS attack would fail miserably as we have a timeout IIRC \o/

**Comment by myrrlyn** [comment]
*Absolutely* do not worry about it; I'm not answering my maintenance calls very well either!

I think my commits from last night (finally found the serializer) are probably more correct w.r.t. program behavior, but now that it's generally applied to all IAL elements rather than a special-case on the class parser, it does allow a user to write `{:#id1 #id2}` and produce `id="id1 id2"` rather than `id="id1id2"`. I suspect this is incorrect HTML, but I think it's fine to say "then don't provide that input" and not guard against it here.

**Comment by RobertDober** [comment]
Actually I have to revert this sorry, your code is not executed, I realized that when adding a test, sorry.

As a side note, I believe that you cannot better `Enum.reverse` in pure Elixir. I am sure it is linear too and probably optimized a little bit ;)

**Comment by RobertDober** [comment]
as you can see the current behavior seems ok to me

```elixir
iex(30)> as_ast("hello\n{:.a .b}")
{:ok, [{"p", [{"class", "b a"}], ["hello"], %{}}], []}
```

Is there something I missed? Does the reversed order have any influence on the HTML's semantic? If that is the case I'll happily accept another PR or fix it myself.

**Comment by myrrlyn** [comment]
No the reversal was purely aesthetic.

----

I went to double check and while I was not able to replicate in a scratch project that only used EarmarkParser, switching back to 1.4.12 from Hex *did* reproduce the error.

image

```elixir
iex(1)> :application.get_key(:earmark_parser, :vsn)
{:ok, '1.4.12'}
iex(2)> "> hello\n{:.a .b}" |> EarmarkParser.as_ast
{:ok, [{"blockquote", [{"class", "ba"}], [{"p", [], ["hello"], %{}}], %{}}], []}
```

I'll try switching to pull from Git instead of Hex and see if that changes

**Comment by RobertDober** [comment]
@myrrlyn I guess I got it it is the blockquote I forgot in my test case, I'll have a whack at it and keep you posted

**Comment by RobertDober** [comment]
OMG:

```
iex(3)> "- hello\n{:.claass .klass}" |> EarmarkParser.as_ast
** (KeyError) key :attrs not found
```

I thaught the parser was robust 😨

**Comment by RobertDober** [comment]
@myrrlyn As I need to fix #36 urgently I will try to reintegrate your contribution with the credit it deserves.

**Comment by myrrlyn** [comment]
Happy to provide pathological input haha. Thanks for your work by the way, Earmark and EarmarkParser continue to be great experiences to use and I'm really happy with them!

**Pull request merged**
